album/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

url(r'^user/(?P<user_id>[0-9]+)/$', views.detail_album, name='detail_album'),
url(r'^albumm/(?P<album_id>[0-9]+)/$', views.detail_album_selected, name='detail_album_selected'),
url(r'^create_album/$', views.create_album, name='create_album'),
url(r'^pic/(?P<album_id>[0-9]+)/create_picture/$', views.create_picture, name='create_picture'),
]

boutique/urls.py
from django.conf.urls import url
from . import views

app_name = 'boutique'

urlpatterns = [
    url(r'^filtrer/$', views.filtrer, name='filtrer'),
    url(r'^discover/(?P<category>[\w\-]+)/$', views.filtrer, name='filtrer'),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<shop_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^product/(?P<filter_by>[a-zA_Z]+)/$', views.products, name='products'),
    url(r'^create_shop/$', views.create_shop, name='create_shop'),
    url(r'^create_wishlist/$', views.create_wishlist, name='create_wishlist'),
    url(r'^(?P<shop_id>[0-9]+)/create_product/$', views.create_product, name='create_product'),
    url(r'^(?P<shop_id>[0-9]+)/delete_product/(?P<product_id>[0-9]+)/$', views.delete_product, name='delete_product'),
    
    url(r'^(?P<shop_id>[0-9]+)/delete_shop/$', views.delete_shop, name='delete_shop'),
    url(r'^duplicate/(?P<id_product>[0-9]+)/$', views.duplicate_product, name='duplicate_product'),
    url(r'^(?P<shop_id>[0-9]+)/edit_product/(?P<product_id>[0-9]+)/$', views.edit_product, name='edit_product'),
    url(r'^(?P<shop_id>[0-9]+)/edit_product/$', views.edit_shop, name='edit_shop'),
    url(r'^(?P<shop_id>[0-9]+)/activate_product/(?P<id_product>[0-9]+)$', views.activate_product, name='activate_product'),
    url(r'^discover_product/(?P<product_id>[0-9]+)/$', views.discover_product, name='discover_product'),
    url(r'^shop/discover_shop/(?P<shop_id>[0-9]+)/$', views.discover_shop, name='discover_shop'),
    url(r'^filtrer_age/$', views.filtrer_age, name='filtrer_age'),
    

    url(r'^all_wishlists/(?P<username>[^/]+)?$', views.all_wishlists, name='all_wishlists'),
    url(r'^user_wishlists/(?P<username>[^/]+)?$', views.user_wishlists, name='user_wishlists'),
    url(r'^(?P<prod_id>[0-9]+)/add_to_wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^discover_wishlist/(?P<wishlist_id>[0-9]+)/$', views.discover_wishlist, name='discover_wishlist'),

]

project/feeds/urls.py
from django.conf.urls import url

from project.feeds import views

urlpatterns = [
    url(r'^$', views.feeds, name='feeds'),
    url(r'^post/$', views.post, name='post'),
    url(r'^like/$', views.like, name='like'),
    url(r'^comment/$', views.comment, name='comment'),
    url(r'^load/$', views.load, name='load'),
    url(r'^check/$', views.check, name='check'),
    url(r'^load_new/$', views.load_new, name='load_new'),
    url(r'^update/$', views.update, name='update'),
    url(r'^track_comments/$', views.track_comments, name='track_comments'),
    url(r'^remove/$', views.remove, name='remove_feed'),
    url(r'^(\d+)/$', views.feed, name='feed'),
]

project/messenger/urls.py
from django.conf.urls import url
from project.messenger import views

urlpatterns = [

	url(r'^attach/$', views.attach, name='attach_product'),
    url(r'^search_modal/$', views.search_modal, name='search_modal'),
    url(r'^$', views.inbox, name='inbox'),
    url(r'^new/$', views.new, name='new_message'),
    url(r'^new2/(?P<prod_id>[^/]+)/$', views.new2, name='new_message2'),
    url(r'^send/$', views.send, name='send_message'),
    url(r'^send_prod/$', views.send_product, name='send_product'),
    url(r'^delete/$', views.delete, name='delete_message'),
    url(r'^users/$', views.users, name='users_message'),
    url(r'^check/$', views.check, name='check_message'),
    url(r'^(?P<username>[^/]+)/$', views.messages, name='messages'),


     
]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from project.authentication import views as project_auth_views
from project.core import views as core_views
from project.authentication import views as bootcamp_auth_views
from django.contrib.auth import views as auth_views
from reactions import views as reactions_views
from notifications import views as notifications_views
from posts import views as posts_views

urlpatterns = [
    
    url(r'^reaction/(?P<pk>\d+)$', reactions_views.react, name='react'),
    url(r'^reaction_post/(?P<pk>\d+)$', reactions_views.react_post, name='react_post'),
    url(r'^admin/', admin.site.urls),
    url(r'^boutique/', include('boutique.urls')),
    url(r'^post/', include('posts.urls')),
    url(r'^album/', include('album.urls')),

    url(r'^', include('boutique.urls')),
   	url(r'^messages/', include('project.messenger.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^feeds/', include('project.feeds.urls')),
    url(r'^$', core_views.home, name='home'),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', bootcamp_auth_views.signup, name='signup'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^aa/(?P<username>[^/]+)/$', core_views.profile, name='profile'),
     url(r'^notifications/$', notifications_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', notifications_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', notifications_views.check_notifications,
        name='check_notifications'),
    
    url(r'^api/notifications/', include("notifications.api.urls", namespace='notifications-api')),
    url(r'^api/messenger/', include("project.messenger.api.urls", namespace='messenger-api')),
    url(r'^api/reactions/', include("reactions.api.urls", namespace='reactions-api')),
    

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/models.py
# Create your models here.

project/messenger/forms.py
from django.contrib.auth.models import User
from django import forms
from project.messenger.models import Picture


class PictureForm(forms.ModelForm):

    class Meta:
        model = Picture
        fields = ['image']

project/authentication/views.py
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.shortcuts import redirect, render

from project.authentication.forms import SignUpForm
from project.feeds.models import Feed


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if not form.is_valid():
            return render(request, 'authentication/signup.html',
                          {'form': form})

        else:
            username = form.cleaned_data.get('username')
            email = form.cleaned_data.get('email')
            password = form.cleaned_data.get('password')
            User.objects.create_user(username=username, password=password,
                                     email=email)
            user = authenticate(username=username, password=password)
            login(request, user)
            welcome_post = '{0} has joined the network.'.format(user.username,
                                                                user.username)
            feed = Feed(user=user, post=welcome_post)
            feed.save()
            return redirect('/')

    else:
        return render(request, 'authentication/signup.html',
                      {'form': SignUpForm()})

project/core/views.py
import os
import json

from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect, render

from project.core.forms import ChangePasswordForm, ProfileForm
from project.feeds.views import FEEDS_NUM_PAGES, feeds
from project.feeds.models import Feed
from project.feeds.views import feeds
from posts.models import Post


# from project.articles.models import Article, ArticleComment
# from project.questions.models import Question, Answer
# from project.activities.models import Activity

from PIL import Image


def home(request):
    if request.user.is_authenticated():
        return feeds(request)
    else:
        return render(request, 'core/cover.html')


@login_required
def network(request):
    users_list = User.objects.filter(is_active=True).order_by('username')
    paginator = Paginator(users_list, 100)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'core/network.html', {'users': users})


@login_required
def profile(request, username):
    page_user = User.objects.get(username=username)
    all_feeds = Feed.get_feeds().filter(user=page_user)
    posts = Post.objects.filter(user=request.user)
    paginator = Paginator(all_feeds, FEEDS_NUM_PAGES)
    feeds = paginator.page(1)
    from_feed = -1
    if feeds:
        from_feed = feeds[0].id

    feeds_count = Feed.objects.filter(user=page_user).count()
    # article_count = Article.objects.filter(create_user=page_user).count()
    # article_comment_count = ArticleComment.objects.filter(
    #     user=page_user).count()
    # question_count = Question.objects.filter(user=page_user).count()
    # answer_count = Answer.objects.filter(user=page_user).count()
    # activity_count = Activity.objects.filter(user=page_user).count()
    # data, datepoints = Activity.daily_activity(page_user)
    data = {
        'page_user': page_user,
        'feeds_count': feeds_count,
        # 'article_count': article_count,
        # 'article_comment_count': article_comment_count,
        # 'question_count': question_count,
        #'global_interactions': activity_count,
        #'answer_count': answer_count,
        # 'bar_data': [feeds_count, article_count, article_comment_count,
        #              question_count, answer_count, activity_count],
        'bar_labels': json.dumps(
            '["Feeds", "Articles", "Comments", "Questions", "Answers", "Activities"]'),
        # 'line_labels': datepoints,
        # 'line_data': data,
        'feeds': feeds,
        'from_feed': from_feed,
        'page': 1,
        'posts': posts
        }
    return render(request, 'core/profile.html', data)


@login_required
def settings(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.profile.job_title = form.cleaned_data.get('job_title')
            user.email = form.cleaned_data.get('email')
            user.profile.url = form.cleaned_data.get('url')
            user.profile.location = form.cleaned_data.get('location')
            user.profile.age = form.cleaned_data.get('age')
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile was successfully edited.')

    else:
        form = ProfileForm(instance=user, initial={
            'job_title': user.profile.job_title,
            'url': user.profile.url,
            'location': user.profile.location
            })
    return render(request, 'core/settings.html', {'form': form})


@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET.get('upload_picture') == 'uploaded':
            uploaded_picture = True

    except Exception:
        pass

    return render(request, 'core/picture.html',
                  {'uploaded_picture': uploaded_picture})


@login_required
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('password')

    else:
        form = ChangePasswordForm(instance=user)

    return render(request, 'core/password.html', {'form': form})


@login_required
def upload_picture(request):
    try:
        profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
        if not os.path.exists(profile_pictures):
            os.makedirs(profile_pictures)
        f = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_tmp.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 350:
            new_width = 350
            new_height = (height * 350) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        return redirect('/settings/picture/?upload_picture=uploaded')

    except Exception as e:
        print(e)
        return redirect('/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        w = int(request.POST.get('w'))
        h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)

    except Exception:
        pass

    return redirect('/settings/picture/')

project/messenger/api/views.py
from django.contrib.auth.models import User
from rest_framework import status, permissions
from rest_framework.decorators import api_view
from rest_framework.generics import ListAPIView
from rest_framework.permissions import AllowAny
from rest_framework.response import Response
from rest_framework.views import APIView

from project.messenger.api.serializers import MessageListSerializer, MessageSendSerializer
from project.messenger.models import Message
from rest_framework.generics import (
    CreateAPIView,
    DestroyAPIView,
    ListAPIView,
    RetrieveAPIView,
    RetrieveUpdateAPIView
    )

class MessageListAPIView(ListAPIView):
    def get(self, request, username, format=None):
        # queryset = self.filter_queryset(self.get_queryset())

        # serializer = self.get_serializer(queryset, many=True)

        print(username)

        messages = Message.objects.filter(user__username=username)

        serializer = MessageListSerializer(messages, many=True)

        serializer_data = serializer.data

        custom_data = {'messages': serializer_data}

        return Response(custom_data)


class MessageSendAPIView(CreateAPIView):
    queryset = Message.objects.all()
    serializer_class = MessageSendSerializer

    def post(self,request,to_user ):
        serializer = MessageSendSerializer(data=request.data)
        serializer2 = MessageSendSerializer(data=request.data)
        user = User.objects.get(username=to_user)
        if serializer.is_valid() and serializer2.is_valid():
            serializer.save(from_user=request.user,user=user,conversation=request.user)
            serializer2.save(from_user=request.user, user=request.user, conversation=user)
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        else:
            return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

project/templates/base.html
{% load staticfiles i18n %}<!DOCTYPE html>
<html lang="en">
  <head>
    <style>
        nav-aa {
            position: absolute;

            bottom: 0px;
            left: 400px;
            top: 670px;
            }
    </style>
    
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{% block title %}Shop{% endblock %}</title>


<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">
<link href="{% static 'css/bootcamp.css' %}?v=1" rel="stylesheet">
 
    
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
<script src="{% static 'js/bootcamp.js' %}"></script>
<link href="{% static 'css/notifications.css' %}" rel="stylesheet">
<script src="{% static 'js/notifications.js' %}"></script>

        <!-- Gender Button -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


{% block head %}{% endblock %}
  </head>

  <body>
    {% block body %}
      <header>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
          <div class="container-fluid">

            <div class="navbar-header">
              <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#topNavBar">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="{% url 'boutique:filtrer' %}">Shop</a>
              <!-- {% if user.profile.age is None %}
              <a class="navbar-brand" href="{% url 'boutique:filtrer' %}">Shop</a>
              {% else %}
              <a class="navbar-brand" href="{% url 'boutique:filtrer_age' %}">Shop</a>
              {% endif %} -->
            </div>

                      <!-- Items of NavBar -->

            <div class="collapse navbar-collapse" id="topNavBar">
              <ul class="nav navbar-nav">
                <li class="{% block produits_active %}{% endblock %}">
                <a href="{% url 'boutique:filtrer' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;All Products</a></li>
                <!-- {% if user.profile.age is None %}
                <a href="{% url 'boutique:filtrer' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;All Products</a></li>
                {% else %}
                <a href="{% url 'boutique:filtrer_age' %}"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span>&nbsp;All Products</a></li>
                {% endif %} -->

                <li class="{% block shops_active %}{% endblock %}"><a href="{% url 'boutique:index' %}"><span class="glyphicon glyphicon-home" aria-hidden="true"></span>&nbsp; My Shop</a></li>
                <li><a href="{% url 'home_user' %}"><span class="glyphicon glyphicon-th"> Home</a></li>
             <!--    <li class="{% block products_active %}{% endblock %}"><a href="{% url 'boutique:products' 'all' %}"><span class="glyphicon glyphicon-th-list" aria-hidden="true"></span>&nbsp;My Products</a></li> -->
                <li>
                  <a href="#" id="notifications" data-container="body" data-toggle="popover" data-placement="bottom" title="Notifications">
                  <span class="glyphicon glyphicon-bell"></span>
                  </a></li>
              </ul>

         
              <ul class="nav navbar-nav navbar-right">
             
                <li>
                  <a href="{% url 'profile' user.username %}"><span class="glyphicon glyphicon-user"></span>  {{ user.profile.get_screen_name }}</a>
                </li>

                   <li>
                {% if user.profile.get_screen_name %}

                  <a href="{% url 'boutique:create_wishlist' %}"><i class="fa fa-shopping-basket fa-lg" aria-hidden="true"></i></a>
                {% endif %}

                </li> 
                
              

                <li>
                  <a href="{% url 'inbox' %}"><span class="badge pull-right" id="unread-count">0</span> Inbox</a>
                </li>
                <li>
                  <a href="{% url 'settings' %}"><span class="glyphicon glyphicon-cog"></span>{% trans 'Account Settings' %}</a>
                </li>    
                <li>
                  <a href="{% url 'boutique:logout_user' %}">
                  <span class="glyphicon glyphicon-off" aria-hidden="true"></span>&nbsp; Logout</a>
                </li>
              </ul>
                               
            </div>
          </div>
        </nav>
      </header>

    <main>
      <div class="container">
        {% block main %}
        {% endblock main %}
      </div>
    </main>

    
    <script src="{% static 'js/check_messages.js' %}"></script>
    
    {% endblock body %}

   <script src="{% static 'js/ga.js' %}"></script>
  </body>
</html>

project/templates/markdown_editor.html
{% load staticfiles %}
<script src="{% static 'js/jquery.selection.js' %}"></script>
<script src="{% static 'js/bootcamp.markdown.js' %}"></script>

<div class="markdown">
  <div class="modal fade" id="markdown_insert_link">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Insert Link</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label for="markdown_link_text" class="control-label">Link Text</label>
            <input type="text" class="form-control" id="markdown_link_text" placeholder="Link Text">
          </div>
          <div class="form-group">
            <label for="markdown_url" class="control-label">URL</label>
            <input type="text" class="form-control" id="markdown_url" placeholder="URL">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary add_link" data-dismiss="modal">Ok</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="markdown_insert_picture">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Insert Image</h4>
        </div>
        <div class="modal-body">
          <div class="form-group">
            <label for="markdown_picture_url" class="control-label">Picture URL</label>
            <input type="text" class="form-control" id="markdown_picture_url" placeholder="Picture URL">
          </div>
          <div class="form-group">
            <label for="markdown_alt_text" class="control-label">Alt Text</label>
            <input type="text" class="form-control" id="markdown_alt_text" placeholder="Alt Text">
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-primary add_picture" data-dismiss="modal">Ok</button>
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="modal fade" id="markdown_help">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
          <h4 class="modal-title">Help</h4>
        </div>
        <div class="modal-body">
          <p>You can learn more about markdown syntax <a href="http://daringfireball.net/projects/markdown/syntax" target="_blank">here</a>.</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>
    </div>
  </div>
  <div class="btn-group">
    <button type="button" class="btn btn-default btn-sm" ref="header"><span class="glyphicon glyphicon-header"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="bold"><span class="glyphicon glyphicon-bold"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="italic"><span class="glyphicon glyphicon-italic"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="list"><span class="glyphicon glyphicon-list"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="link"><span class="glyphicon glyphicon-link"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="picture"><span class="glyphicon glyphicon-picture"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="indent-left"><span class="glyphicon glyphicon-indent-left"></span></button>
    <button type="button" class="btn btn-default btn-sm" ref="indent-right"><span class="glyphicon glyphicon-indent-right"></span></button>
  </div>
  <button type="button" data-toggle="modal" data-target="#markdown_help" class="btn btn-link btn-sm pull-right"><span class="glyphicon glyphicon-question-sign"></span> Help</button>
</div>
<script>$(function(){$("#{{ textarea }}").markdown();});</script>

project/templates/paginator.html
<ul class="pagination">
  {% if paginator.has_previous %}
    <li><a href="?page={{ paginator.previous_page_number }}">&laquo;</a></li>
  {% else %}
    <li class="disabled"><span>&laquo;</span></li>
  {% endif %}
  {% for i in paginator.paginator.page_range %}
    {% if paginator.number == i %}
      <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
    {% else %}
      <li><a href="?page={{ i }}">{{ i }}</a></li>
    {% endif %}
  {% endfor %}
  {% if paginator.has_next %}
    <li><a href="?page={{ paginator.next_page_number }}">&raquo;</a></li>
  {% else %}
    <li class="disabled"><span>&raquo;</span></li>
  {% endif %}
</ul>