album/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

url(r'^user/(?P<user_id>[0-9]+)/$', views.detail_album, name='detail_album'),
url(r'^albumm/(?P<album_id>[0-9]+)/$', views.detail_album_selected, name='detail_album_selected'),
url(r'^create_album/$', views.create_album, name='create_album'),
url(r'^pic/(?P<album_id>[0-9]+)/create_picture/$', views.create_picture, name='create_picture'),
]

boutique/urls.py
from django.conf.urls import url
from . import views

app_name = 'boutique'

urlpatterns = [
    url(r'^filtrer/$', views.filtrer, name='filtrer'),
    url(r'^discover/(?P<category>[\w\-]+)/$', views.filtrer, name='filtrer'),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<shop_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^product/(?P<filter_by>[a-zA_Z]+)/$', views.products, name='products'),
    url(r'^create_shop/$', views.create_shop, name='create_shop'),
    url(r'^create_wishlist/$', views.create_wishlist, name='create_wishlist'),
    url(r'^(?P<shop_id>[0-9]+)/create_product/$', views.create_product, name='create_product'),
    url(r'^(?P<shop_id>[0-9]+)/delete_product/(?P<product_id>[0-9]+)/$', views.delete_product, name='delete_product'),
    
    url(r'^(?P<shop_id>[0-9]+)/delete_shop/$', views.delete_shop, name='delete_shop'),
    url(r'^duplicate/(?P<id_product>[0-9]+)/$', views.duplicate_product, name='duplicate_product'),
    url(r'^(?P<shop_id>[0-9]+)/edit_product/(?P<product_id>[0-9]+)/$', views.edit_product, name='edit_product'),
    url(r'^(?P<shop_id>[0-9]+)/edit_product/$', views.edit_shop, name='edit_shop'),
    url(r'^(?P<shop_id>[0-9]+)/activate_product/(?P<id_product>[0-9]+)$', views.activate_product, name='activate_product'),
    url(r'^discover_product/(?P<product_id>[0-9]+)/$', views.discover_product, name='discover_product'),
    url(r'^shop/discover_shop/(?P<shop_id>[0-9]+)/$', views.discover_shop, name='discover_shop'),
    url(r'^filtrer_age/$', views.filtrer_age, name='filtrer_age'),
    

    url(r'^all_wishlists/(?P<username>[^/]+)?$', views.all_wishlists, name='all_wishlists'),
    url(r'^user_wishlists/(?P<username>[^/]+)?$', views.user_wishlists, name='user_wishlists'),
    url(r'^(?P<prod_id>[0-9]+)/add_to_wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^discover_wishlist/(?P<wishlist_id>[0-9]+)/$', views.discover_wishlist, name='discover_wishlist'),

]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from project.authentication import views as project_auth_views
from project.core import views as core_views
from project.authentication import views as bootcamp_auth_views
from django.contrib.auth import views as auth_views
from reactions import views as reactions_views
from notifications import views as notifications_views
from posts import views as posts_views

urlpatterns = [
    
    url(r'^reaction/(?P<pk>\d+)$', reactions_views.react, name='react'),
    url(r'^reaction_post/(?P<pk>\d+)$', reactions_views.react_post, name='react_post'),
    url(r'^admin/', admin.site.urls),
    url(r'^boutique/', include('boutique.urls')),
    url(r'^post/', include('posts.urls')),
    url(r'^album/', include('album.urls')),

    url(r'^', include('boutique.urls')),
   	url(r'^messages/', include('project.messenger.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^feeds/', include('project.feeds.urls')),
    url(r'^$', core_views.home, name='home'),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', bootcamp_auth_views.signup, name='signup'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^aa/(?P<username>[^/]+)/$', core_views.profile, name='profile'),
     url(r'^notifications/$', notifications_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', notifications_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', notifications_views.check_notifications,
        name='check_notifications'),
    
    url(r'^api/notifications/', include("notifications.api.urls", namespace='notifications-api')),
    url(r'^api/messenger/', include("project.messenger.api.urls", namespace='messenger-api')),
    url(r'^api/reactions/', include("reactions.api.urls", namespace='reactions-api')),
    

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

project/core/models.py
# Create your models here.

project/core/forms.py
from django import forms
from django.contrib.auth.models import User


class ProfileForm(forms.ModelForm):
    

    first_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=False)
    last_name = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=30,
        required=False)
    job_title = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)
    email = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=75,
        required=False)
    url = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)
    location = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=50,
        required=False)
    age = forms.CharField(
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=10,
        required=False)

    gender = forms.CharField(
        
        widget=forms.TextInput(attrs={'class': 'form-control'}),
        max_length=15,
        required=False)
    
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'job_title',
                  'email', 'url', 'location','age', 'gender']


class ChangePasswordForm(forms.ModelForm):
    id = forms.CharField(widget=forms.HiddenInput())
    old_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Old password",
        required=True)

    new_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="New password",
        required=True)
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(attrs={'class': 'form-control'}),
        label="Confirm new password",
        required=True)

    class Meta:
        model = User
        fields = ['id', 'old_password', 'new_password', 'confirm_password']

    def clean(self):
        super(ChangePasswordForm, self).clean()
        old_password = self.cleaned_data.get('old_password')
        new_password = self.cleaned_data.get('new_password')
        confirm_password = self.cleaned_data.get('confirm_password')
        id = self.cleaned_data.get('id')
        user = User.objects.get(pk=id)
        if not user.check_password(old_password):
            self._errors['old_password'] = self.error_class([
                'Old password don\'t match'])
        if new_password and new_password != confirm_password:
            self._errors['new_password'] = self.error_class([
                'Passwords don\'t match'])
        return self.cleaned_data

project/core/views.py
import os
import json

from django.conf import settings as django_settings
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.shortcuts import redirect, render

from project.core.forms import ChangePasswordForm, ProfileForm
from project.feeds.views import FEEDS_NUM_PAGES, feeds
from project.feeds.models import Feed
from project.feeds.views import feeds
from posts.models import Post


# from project.articles.models import Article, ArticleComment
# from project.questions.models import Question, Answer
# from project.activities.models import Activity

from PIL import Image


def home(request):
    if request.user.is_authenticated():
        return feeds(request)
    else:
        return render(request, 'core/cover.html')


@login_required
def network(request):
    users_list = User.objects.filter(is_active=True).order_by('username')
    paginator = Paginator(users_list, 100)
    page = request.GET.get('page')
    try:
        users = paginator.page(page)
    except PageNotAnInteger:
        users = paginator.page(1)
    except EmptyPage:
        users = paginator.page(paginator.num_pages)
    return render(request, 'core/network.html', {'users': users})


@login_required
def profile(request, username):
    page_user = User.objects.get(username=username)
    all_feeds = Feed.get_feeds().filter(user=page_user)
    posts = Post.objects.filter(user=request.user)
    paginator = Paginator(all_feeds, FEEDS_NUM_PAGES)
    feeds = paginator.page(1)
    from_feed = -1
    if feeds:
        from_feed = feeds[0].id

    feeds_count = Feed.objects.filter(user=page_user).count()
    # article_count = Article.objects.filter(create_user=page_user).count()
    # article_comment_count = ArticleComment.objects.filter(
    #     user=page_user).count()
    # question_count = Question.objects.filter(user=page_user).count()
    # answer_count = Answer.objects.filter(user=page_user).count()
    # activity_count = Activity.objects.filter(user=page_user).count()
    # data, datepoints = Activity.daily_activity(page_user)
    data = {
        'page_user': page_user,
        'feeds_count': feeds_count,
        # 'article_count': article_count,
        # 'article_comment_count': article_comment_count,
        # 'question_count': question_count,
        #'global_interactions': activity_count,
        #'answer_count': answer_count,
        # 'bar_data': [feeds_count, article_count, article_comment_count,
        #              question_count, answer_count, activity_count],
        'bar_labels': json.dumps(
            '["Feeds", "Articles", "Comments", "Questions", "Answers", "Activities"]'),
        # 'line_labels': datepoints,
        # 'line_data': data,
        'feeds': feeds,
        'from_feed': from_feed,
        'page': 1,
        'posts': posts
        }
    return render(request, 'core/profile.html', data)


@login_required
def settings(request):
    user = request.user
    if request.method == 'POST':
        form = ProfileForm(request.POST)
        if form.is_valid():
            user.first_name = form.cleaned_data.get('first_name')
            user.last_name = form.cleaned_data.get('last_name')
            user.profile.job_title = form.cleaned_data.get('job_title')
            user.email = form.cleaned_data.get('email')
            user.profile.url = form.cleaned_data.get('url')
            user.profile.location = form.cleaned_data.get('location')
            user.profile.age = form.cleaned_data.get('age')
            user.save()
            messages.add_message(request,
                                 messages.SUCCESS,
                                 'Your profile was successfully edited.')

    else:
        form = ProfileForm(instance=user, initial={
            'job_title': user.profile.job_title,
            'url': user.profile.url,
            'location': user.profile.location
            })
    return render(request, 'core/settings.html', {'form': form})


@login_required
def picture(request):
    uploaded_picture = False
    try:
        if request.GET.get('upload_picture') == 'uploaded':
            uploaded_picture = True

    except Exception:
        pass

    return render(request, 'core/picture.html',
                  {'uploaded_picture': uploaded_picture})


@login_required
def password(request):
    user = request.user
    if request.method == 'POST':
        form = ChangePasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('new_password')
            user.set_password(new_password)
            user.save()
            update_session_auth_hash(request, user)
            messages.add_message(request, messages.SUCCESS,
                                 'Your password was successfully changed.')
            return redirect('password')

    else:
        form = ChangePasswordForm(instance=user)

    return render(request, 'core/password.html', {'form': form})


@login_required
def upload_picture(request):
    try:
        profile_pictures = django_settings.MEDIA_ROOT + '/profile_pictures/'
        if not os.path.exists(profile_pictures):
            os.makedirs(profile_pictures)
        f = request.FILES['picture']
        filename = profile_pictures + request.user.username + '_tmp.jpg'
        with open(filename, 'wb+') as destination:
            for chunk in f.chunks():
                destination.write(chunk)
        im = Image.open(filename)
        width, height = im.size
        if width > 350:
            new_width = 350
            new_height = (height * 350) / width
            new_size = new_width, new_height
            im.thumbnail(new_size, Image.ANTIALIAS)
            im.save(filename)

        return redirect('/settings/picture/?upload_picture=uploaded')

    except Exception as e:
        print(e)
        return redirect('/settings/picture/')


@login_required
def save_uploaded_picture(request):
    try:
        x = int(request.POST.get('x'))
        y = int(request.POST.get('y'))
        w = int(request.POST.get('w'))
        h = int(request.POST.get('h'))
        tmp_filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '_tmp.jpg'
        filename = django_settings.MEDIA_ROOT + '/profile_pictures/' +\
            request.user.username + '.jpg'
        im = Image.open(tmp_filename)
        cropped_im = im.crop((x, y, w+x, h+y))
        cropped_im.thumbnail((200, 200), Image.ANTIALIAS)
        cropped_im.save(filename)
        os.remove(tmp_filename)

    except Exception:
        pass

    return redirect('/settings/picture/')

project/core/templates/core/cover.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block head %}
  <link href="{% static 'css/cover.css' %}" rel="stylesheet">
{% endblock head %}

{% block body %}
  <a href="https://github.com/vitorfs/bootcamp"><img style="position: absolute; top: 0; right: 0; border: 0;" src="https://camo.githubusercontent.com/e7bbb0521b397edbd5fe43e7f760759336b5e05f/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f6769746875622f726962626f6e732f666f726b6d655f72696768745f677265656e5f3030373230302e706e67" alt="Fork me on GitHub" data-canonical-src="https://s3.amazonaws.com/github/ribbons/forkme_right_green_007200.png"></a>
  <div class="cover">
    <h1 class="logo">Bootcamp</h1>
    {% if form.non_field_errors %}
      {% for error in form.non_field_errors %}
        <div class="alert alert-danger alert-dismissable">
          <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
          {{ error }}
        </div>
      {% endfor %}
    {% endif %}
    <div class="login">
      <h2>{% trans 'Log in' %}</h2>
      <form method="post" action="{% url 'login' %}" role="form">
        {% csrf_token %}
        <div class="form-group{% if form.username.errors %} has-error{% endif %}">
          <label for="username">{% trans 'Username' %}</label>
          <input type="text" class="form-control" id="username" name="username">
          {% for error in form.username.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group{% if form.password.errors %} has-error{% endif %}">
          <label for="password">{% trans 'Password' %}</label>
          <input type="password" class="form-control" id="password" name="password">
          {% for error in form.password.errors %}
            <label class="control-label">{{ error }}</label>
          {% endfor %}
        </div>
        <div class="form-group">
          <button type="submit" class="btn btn-default">{% trans 'Log in' %}</button>
          <a href="{% url 'signup' %}" class="btn btn-link">{% trans 'Sign up for Bootcamp' %}</a>
        </div>
      </form>
    </div>
  </div>
{% endblock body %}

project/core/templates/core/network.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{% trans 'Network' %}{% endblock %}

{% block head %}
  <link href="{% static 'css/network.css' %}" rel="stylesheet">
{% endblock head %}

{% block main %}
  <div class="page-header">
    <h1>Network</h1>
  </div>
  <div class="users">

    <div class="row">
      {% for user in users %}
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading">
              <img src="{{ user.profile.get_picture }}" style="width:20px">
              <a href="{% url 'profile' user.username %}">{{ user.profile.get_screen_name }}</a>
            </div>
            <div class="panel-body">
              {% if user.profile.job_title %}
                <p><strong>{% trans 'Job Title' %}:</strong> {{ user.profile.job_title }}</p>
              {% endif %}
              <p><strong>{% trans 'Username' %}: </strong> {{ user.username }}</p>
              {% if user.profile.location %}
                <p><strong>{% trans 'Location' %}:</strong> {{ user.profile.location }}</p>
              {% endif %}
              {% if user.profile.url %}
                <p><strong>{% trans 'Url' %}:</strong> {{ user.profile.get_url }}</p>
              {% endif %}
            </div>
          </div>
        </div>
        {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
      {% endfor %}
    </div>

    <div class="row">
      <div class="col-md-12">
        {% include 'paginator.html' with paginator=users %}
      </div>
    </div>

  </div>
{% endblock main %}

project/core/templates/core/partial_settings_menu.html
{% load i18n %}
<div class="list-group">
  <a href="{% url 'settings' %}" class="list-group-item{% if active == 'profile' %} active{% endif %}">{% trans 'Profile' %}</a>
  <a href="{% url 'picture' %}" class="list-group-item{% if active == 'picture' %} active{% endif %}">{% trans 'Picture' %}</a>
  <a href="{% url 'password' %}" class="list-group-item{% if active == 'password' %} active{% endif %}">{% trans 'Password' %}</a>
</div>

project/core/templates/core/password.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block main %}
  <div class="page-header">
  <br>
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'core/partial_settings_menu.html' with active='password' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Password' %}</h3>
      <form role="form" class="form-horizontal" method="post" action="{% url 'password' %}">
        {% csrf_token %}
        {{ form.id }}
        {% for field in form.visible_fields %}
          <div class="form-group{% if field.errors %} has-error{% endif %}">
            <label for="{{ field.label }}" class="col-sm-3 control-label">{{ field.label }}</label>
            <div class="col-sm-9">
              {{ field }}
              {% if field.help_text %}
                <span class="help-block">{{ field.help_text }}</span>
              {% endif %}
              {% for error in field.errors %}
                <label class="control-label">{{ error }}</label>
              {% endfor %}
            </div>
          </div>
        {% endfor %}
        <div class="form-group">
          <div class="col-sm-offset-3 col-sm-9">
            <button type="submit" class="btn btn-primary">{% trans 'Save' %}</button>
          </div>
        </div>
      </form>
    </div>
  </div>
{% endblock main %}

project/core/templates/core/picture.html
{% extends 'base.html' %}

{% load i18n static %}

{% block title %}{% trans 'Account Settings' %}{% endblock %}

{% block head %}
  <link href="{% static 'css/jquery.Jcrop.min.css' %}" rel="stylesheet">
  <script src="{% static 'js/jquery.Jcrop.min.js' %}"></script>
  <script src="{% static 'js/picture.js' %}"></script>
{% endblock head %}

{% block main %}
  <div class="page-header">
  <br>
    <h1>{% trans 'Account Settings' %}</h1>
  </div>
  <div class="row" style="margin-top: 2em">
    <div class="col-md-3">
      {% include 'core/partial_settings_menu.html' with active='picture' %}
    </div>
    <div class="col-md-9">
      {% if messages %}
        {% for message in messages %}
          <div class="alert alert-success alert-dismissable">
            <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
            {{ message }}
          </div>
        {% endfor %}
      {% endif %}
      <h3 style="margin-top: 0">{% trans 'Change Picture' %}</h3>
      <img src="{{ user.profile.get_picture }}" style="width: 150px; border-radius: 5px; margin-bottom: 1em;">
      <form enctype="multipart/form-data" method="post" action="{% url 'upload_picture' %}" id="picture-upload-form">
        {% csrf_token %}
        <input type="file" name="picture" style="display: none">
        <button type="button" class="btn btn-default" id="btn-upload-picture">{% trans 'Upload new picture' %}</button>
      </form>

      {% if uploaded_picture %}
        <form method="post" action="{% url 'save_uploaded_picture' %}">
          {% csrf_token %}
          <div class="modal fade" id="modal-upload-picture">
            <div class="modal-dialog">
              <div class="modal-content">
                <div class="modal-header">
                  <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                  <h4 class="modal-title">{% trans 'Crop Picture' %}</h4>
                </div>
                <div class="modal-body">
                  <div class="selected-picture">
                    <p>{% trans 'Crop the profile picture and then click on the' %} <strong>{% trans 'Save Picture' %}</strong> {% trans 'button' %}</p>
                    <img src="{% get_media_prefix %}profile_pictures/{{ user.username }}_tmp.jpg?_={% now 'U' %}" id="crop-picture">
                    <input type="hidden" id="x" name="x" />
                    <input type="hidden" id="y" name="y" />
                    <input type="hidden" id="w" name="w" />
                    <input type="hidden" id="h" name="h" />
                  </div>
                  <script type="text/javascript">
                    $(function () {
                      $("#modal-upload-picture").modal();
                      window.history.pushState("", "", "/settings/picture/");
                    });
                  </script>
                </div>
                <div class="modal-footer">
                  <button type="button" class="btn btn-default" data-dismiss="modal">{% trans 'Close' %}</button>
                  <button type="submit" class="btn btn-primary">{% trans 'Save changes' %}</button>
                </div>
              </div>
            </div>
          </div>
        </form>
      {% endif %}
    </div>
  </div>
{% endblock main %}

project/core/templates/core/profile.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load i18n %}

{% block title %}{{ page_user.profile.get_screen_name }}{% endblock %}

{% block head %}
  <link href="{% static 'css/profile.css' %}" rel="stylesheet">
  <link href="{% static 'css/feeds.css' %}" rel="stylesheet">
  <link href="{% static 'css/top_tiles.css' %}" rel="stylesheet">
  <script src="{% static 'js/feeds.js' %}"></script>
  <script src="{% static 'js/jquery.bullseye-1.0-min.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js" type="text/javascript"></script>
  <link href="{% static 'css/notifications.css' %}" rel="stylesheet">
{% endblock head %}
{% block extrahead %}

{% endblock extrahead %}
{% block main %}

  <div class="page-header">
  <br>
    <h1>{{ page_user.profile.get_screen_name }} {% if page_user.get_full_name %}<small>({{ page_user.username }})</small>{% endif %}</h1>
  </div>
  
    <div class="row">
      <!--Profile Name-->
      <div class="col-md-3 user-profile">
        <img src="{{ page_user.profile.get_picture }}" class="picture">
        <ul>
          {% if page_user.profile.job_title %}
          <li><span class="glyphicon glyphicon-briefcase"></span> {{ page_user.profile.job_title }}</li>
          {% endif %}
          {% if page_user.profile.location %}
          <li><span class="glyphicon glyphicon-map-marker"></span> {{ page_user.profile.location }}</li>
          {% endif %}
          {% if page_user.profile.url %}
          <li><span class="glyphicon glyphicon-globe"></span> <a href="{{ page_user.profile.get_url }}" target="_blank">{{ page_user.profile.get_url }}</a></li>
          {% endif %}
        </ul>
      </div>
      <!--Profile Name-->
      <!--Bar graphic chart-->
      <div class="col-md-9">
          <ul class="nav nav-pills">
          {% if page_user.profile.get_screen_name == user.username %} 
            <li class="active"><a  href="#1b" data-toggle="tab">{% trans 'Last Posts' %}</a></li>
            <li>
            {% else %}
            <li><a href="{% url 'user_posts' page_user.profile.user %}" class="btn btn-primary  " role="button"> <B><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Posts of {{ page_user.profile.user.profile.get_screen_name }} </B></a></li>
            {% endif %}


            
            <li><a href="{% url 'detail_album'  page_user.profile.user.id %}" class="btn btn-primary " role="button">
            <span class="glyphicon glyphicon-camera" aria-hidden="true"> Albums</span>  
            </a></li>
           
         
            <!-- <li><a href="#3b" data-toggle="ta
            b">Activity by day</a></li> -->
            
            {% if page_user.profile.get_screen_name == user.username %}           
            <li><a href="{% url 'create_album' %}">
            <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>&nbsp;Add Album
            </a></li>
            
            <li><a href="{% url 'create_post' %}">      
            <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>&nbsp; Add Post
            </a></li>
            {% endif %}

            {% if page_user.profile.get_screen_name == user.username %}
            <li><a href="{% url 'boutique:user_wishlists' user.username %}"><i class="fa fa-user" aria-hidden="true"></i> My wishlists</a></li>
            {% else %}
            <li><a href="{% url 'boutique:user_wishlists' page_user.profile.user %}"><i class="fa fa-user" aria-hidden="true"></i> Wishlist of {{page_user.profile.user.profile.get_screen_name}}</a></li>
            {% endif %}
            
          </ul>
          {% if page_user.profile.get_screen_name == user.username %} 
          <div class="col-sm-4 col-md-9">
            <div class="tab-content">
              <div class="tab-pane active" id="1b">
                <div class="post">
                  {% include 'posts/discover_post.html' with posts=posts %}
                </div>
              </div>  
            </div>
          </div>
          {% endif %}
          <div class="col-sm-4 col-md-7">
            <div class="tab-content">
              <div class="tab-pane active" id="2b">
                 
              </div>  
            </div>
          </div>
                      
              <div class="tab-pane" id="2b">
                <!--Bar graphic chart-->
                <canvas id="bar_chart" width="400" height="160"></canvas>
                <div class="load"><img src="{% static 'images/loading.gif' %}"></div>
              <!--Bar graphic chart-->
                </div>
              </div>

              <div class="tab-pane" id="3b">
              <!--Line graph-->
                <canvas id="line_chart" width="400" height="160"></canvas>
                <div class="load"><img src="{% static 'img/loading.gif' %}"></div>
              <!--Line graph-->
                </div>
              </div>
      </div>
    

    <script type="text/javascript">
      var bar_labels = JSON.parse({{ bar_labels|safe }});
      var bar_data = {{ bar_data }};
      var line_data = {{ line_data|safe }};
      var line_labels = {{ line_labels|safe }};
    </script>
    <script src="{% static 'js/graph_data.js' %}"></script>
    <script src="{% static 'js/send_post.js' %}"></script>
  </div>
{% endblock main %}