album/urls.py
from django.conf.urls import url
from . import views


urlpatterns = [

url(r'^user/(?P<user_id>[0-9]+)/$', views.detail_album, name='detail_album'),
url(r'^albumm/(?P<album_id>[0-9]+)/$', views.detail_album_selected, name='detail_album_selected'),
url(r'^create_album/$', views.create_album, name='create_album'),
url(r'^pic/(?P<album_id>[0-9]+)/create_picture/$', views.create_picture, name='create_picture'),
]

boutique/urls.py
from django.conf.urls import url
from . import views

app_name = 'boutique'

urlpatterns = [
    url(r'^filtrer/$', views.filtrer, name='filtrer'),
    url(r'^discover/(?P<category>[\w\-]+)/$', views.filtrer, name='filtrer'),
    url(r'^$', views.index, name='index'),
    url(r'^register/$', views.register, name='register'),
    url(r'^login_user/$', views.login_user, name='login_user'),
    url(r'^logout_user/$', views.logout_user, name='logout_user'),
    url(r'^(?P<shop_id>[0-9]+)/$', views.detail, name='detail'),

    url(r'^product/(?P<filter_by>[a-zA_Z]+)/$', views.products, name='products'),
    url(r'^create_shop/$', views.create_shop, name='create_shop'),
    url(r'^create_wishlist/$', views.create_wishlist, name='create_wishlist'),
    url(r'^(?P<shop_id>[0-9]+)/create_product/$', views.create_product, name='create_product'),
    url(r'^(?P<shop_id>[0-9]+)/delete_product/(?P<product_id>[0-9]+)/$', views.delete_product, name='delete_product'),
    
    url(r'^(?P<shop_id>[0-9]+)/delete_shop/$', views.delete_shop, name='delete_shop'),
    url(r'^duplicate/(?P<id_product>[0-9]+)/$', views.duplicate_product, name='duplicate_product'),
    url(r'^(?P<shop_id>[0-9]+)/edit_product/(?P<product_id>[0-9]+)/$', views.edit_product, name='edit_product'),
    url(r'^(?P<shop_id>[0-9]+)/edit_product/$', views.edit_shop, name='edit_shop'),
    url(r'^(?P<shop_id>[0-9]+)/activate_product/(?P<id_product>[0-9]+)$', views.activate_product, name='activate_product'),
    url(r'^discover_product/(?P<product_id>[0-9]+)/$', views.discover_product, name='discover_product'),
    url(r'^shop/discover_shop/(?P<shop_id>[0-9]+)/$', views.discover_shop, name='discover_shop'),
    url(r'^filtrer_age/$', views.filtrer_age, name='filtrer_age'),
    

    url(r'^all_wishlists/(?P<username>[^/]+)?$', views.all_wishlists, name='all_wishlists'),
    url(r'^user_wishlists/(?P<username>[^/]+)?$', views.user_wishlists, name='user_wishlists'),
    url(r'^(?P<prod_id>[0-9]+)/add_to_wishlist/$', views.add_to_wishlist, name='add_to_wishlist'),
    url(r'^discover_wishlist/(?P<wishlist_id>[0-9]+)/$', views.discover_wishlist, name='discover_wishlist'),

]

project/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from project.authentication import views as project_auth_views
from project.core import views as core_views
from project.authentication import views as bootcamp_auth_views
from django.contrib.auth import views as auth_views
from reactions import views as reactions_views
from notifications import views as notifications_views
from posts import views as posts_views

urlpatterns = [
    
    url(r'^reaction/(?P<pk>\d+)$', reactions_views.react, name='react'),
    url(r'^reaction_post/(?P<pk>\d+)$', reactions_views.react_post, name='react_post'),
    url(r'^admin/', admin.site.urls),
    url(r'^boutique/', include('boutique.urls')),
    url(r'^post/', include('posts.urls')),
    url(r'^album/', include('album.urls')),

    url(r'^', include('boutique.urls')),
   	url(r'^messages/', include('project.messenger.urls')),
    url(r'^i18n/', include('django.conf.urls.i18n', namespace='i18n')),
    url(r'^settings/password/$', core_views.password, name='password'),
    url(r'^network/$', core_views.network, name='network'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^feeds/', include('project.feeds.urls')),
    url(r'^$', core_views.home, name='home'),
    url(r'^login', auth_views.login, {'template_name': 'core/cover.html'},
        name='login'),
    url(r'^logout', auth_views.logout, {'next_page': '/'}, name='logout'),
    url(r'^signup/$', bootcamp_auth_views.signup, name='signup'),
    url(r'^settings/$', core_views.settings, name='settings'),
    url(r'^settings/picture/$', core_views.picture, name='picture'),
    url(r'^settings/upload_picture/$', core_views.upload_picture,
        name='upload_picture'),
    url(r'^settings/save_uploaded_picture/$', core_views.save_uploaded_picture,
        name='save_uploaded_picture'),
    url(r'^aa/(?P<username>[^/]+)/$', core_views.profile, name='profile'),
     url(r'^notifications/$', notifications_views.notifications,
        name='notifications'),
    url(r'^notifications/last/$', notifications_views.last_notifications,
        name='last_notifications'),
    url(r'^notifications/check/$', notifications_views.check_notifications,
        name='check_notifications'),
    
    url(r'^api/notifications/', include("notifications.api.urls", namespace='notifications-api')),
    url(r'^api/messenger/', include("project.messenger.api.urls", namespace='messenger-api')),
    url(r'^api/reactions/', include("reactions.api.urls", namespace='reactions-api')),
    

]


if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

boutique/models.py
from django.contrib.auth.models import Permission, User
from django.db import models
from django.conf import settings
from django.utils import timezone





class Commercant(models.Model):
    user = models.OneToOneField(User, on_delete = models.CASCADE)
    name = models.CharField(max_length=250, default=None)
    description = models.TextField(max_length=250, default=None)
    tel = models.IntegerField(default=None)
    picture = models.ImageField()

    def __str__(self):
        return self.name



class Shop(models.Model):
    user = models.ForeignKey(User, default=1)
    username = models.CharField(max_length=250)
    shop_name = models.CharField(max_length=500)
    shop_logo = models.FileField(null=True)
    is_favorite = models.BooleanField(default=False)
    visitors = models.ManyToManyField(User,related_name='user')
    Msg_Parametre = models.TextField(default='Can I help you?')

    def __str__(self):
        return self.shop_name + ' - ' + self.username


class Category(models.Model):
    label = models.CharField(
        max_length=250, 
        unique=True 
    )

    def __str__(self):
        return self.label



def user_directory_path(instance, filename):
    return 'user_{0}/{1}/{2}'.format(instance.shop.user.username, instance.shop.shop_name, str(timezone.now)+str(filename))


class Product(models.Model):

    Hand_Made = 'Hand_Made'
    Vintage = 'Vintage'
    Baby = 'Baby'
    Child = 'Child'
    Teenager = 'Teenager'
    Adult = 'Adult'
    Male = 'Male'
    Female = 'Female'
            

    shop = models.ForeignKey(Shop, on_delete=models.CASCADE)
    product_name = models.CharField(max_length=250)
    product_price = models.FloatField()  
    product_logo = models.ImageField(null=True, upload_to=user_directory_path)
    product_pic1 = models.ImageField(null=True, upload_to=user_directory_path)
    product_pic2 = models.ImageField(null=True, upload_to=user_directory_path)
    product_pic3 = models.ImageField(null=True, upload_to=user_directory_path)
    is_activate = models.BooleanField(default=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=None,
        blank=True)
    product_type = models.CharField(
        max_length=20,
        blank=True,
        choices=(
            (Hand_Made, 'Hand_Made'),
            (Vintage, 'Vintage')
        ),default=None
    )
    gender = models.CharField(
        max_length=15,
        blank=True,
        choices=(
            (Male, 'Male'),
            (Female, 'Female')
        ),default=None
    )
    age = models.CharField(
        max_length=10,
        blank=True,
        choices=(
            (Baby, 'Baby'),
            (Child, 'Child'),
            (Teenager, 'Teenager'),
            (Adult, 'Adult')
        ),default=None
    )
    description = models.TextField(max_length=250, default=None)
    quantite = models.IntegerField(default=None)
    date = models.DateField(auto_now_add=True, null=True)
    tags = models.TextField(max_length=250, blank=True, default=None,null=True)
    is_favorite = models.BooleanField(default=False)

    def __str__(self):
        return self.product_name

    class Meta:
        ordering = ('-date',)


class Wishlist(models.Model):
    user = models.ForeignKey(User)
    product = models.ManyToManyField(Product,blank=True, null=True)
    name = models.CharField(max_length=250, default=None)

    def __str__(self):
        return self.name

class Picture(models.Model):
    product = models.ForeignKey(Product)
    name = models.ImageField(blank=True,null=True)





        

boutique/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Shop, Product, Commercant, Wishlist


class WishListForm(forms.ModelForm):

    class Meta:
        model = Wishlist
        fields = ['name']


class ShopForm(forms.ModelForm):

    class Meta:
        model = Shop
        fields = ['shop_name', 'shop_logo']


class ProductForm(forms.ModelForm):

    class Meta:
        model = Product
        fields = ['product_name', 'product_price', 'product_logo','product_pic1', 'product_pic2','product_pic3', 'product_type', 'gender', 'category', 'age', 'description', 'tags', 'quantite', 'is_activate']


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ['username', 'email', 'password']


class CommercantForm(forms.ModelForm):

    class Meta:
        model = Commercant
        fields = ['name', 'description', 'picture', 'tel' ]

boutique/templates/boutique/create_product.html
{% extends 'boutique/base.html' %}
{% block title %}Add a New Product{% endblock %}
{% block shops_active %}active{% endblock %}

{% block body %}
<br><br><br><br>
<div class="container-fluid">

    <div class="row">

        <!-- Left Album Info -->
        <div class="col-sm-4 col-md-3">
            <div class="panel panel-default">
                <div class="panel-body">
                        <a href="{% url 'boutique:detail' shop.id %}">
                            {% if shop.shop_logo %}
                                <img src="{{ shop.shop_logo.url }}" class="img-responsive"></a>
                                <h1>{{ shop.shop_name }} <br><small>{{ user.username }}</small></h1>
                            {% else %}
                                <h3>No image to display</h3>
                            {% endif %}
                        
                    
                </div>
            </div>
        </div>

        <!-- Right Product Info -->
        <div class="col-sm-8 col-md-9">

            <ul class="nav nav-pills" style="margin-bottom: 10px;">
                <li role="presentation"><a href="{% url 'boutique:detail' shop.id %}">View All</a></li>
                <li role="presentation" class="active"><a href="{% url 'boutique:create_product' shop.id %}">Add New Product</a></li>
            </ul>

            <div class="panel panel-default">
                <div class="panel-body">
                    <h3>Add a New Product</h3>
                    {% if error_message %}
                        <p><strong>{{ error_message }}</strong></p>
                    {% endif %}
                    <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="shop" value="{{ shop }}">
                        {% include 'boutique/form_template.html' %}
                        <div class="form-group">
                            <div class="col-sm-offset-2 col-sm-10">
                                <button type="submit" class="btn btn-success">Submit</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>

        </div>

    </div>

</div>

{% endblock %}

boutique/templates/boutique/detailprod.html
{% extends 'boutique/base.html' %}
{% block title %}Products{% endblock %}
{% block shops_active %}active{% endblock %}


{% block body %}
	<div class="container-fluid products-container">
		<div class="row">

			<!-- Left Info -->
			<div class="col-sm-4 col-md-3">
				<div class="panel panel-default">
					<div class="panel-body">
						<a href="{% url 'boutique:product_detail' shop.id %}">
							<img src="{{ shop.shop_logo.url }}" class="img-responsive">
						</a>

						<h1>{{ shop.product_name }}</h1>
							<small>{{ shop.product_price }}</small>
						
					</div>
				</div>
			</div>	
			<!-- Right Info -->
			<div class="col-sm-8 col-md-9">

				<ul class="nav nav-pills" style="margin-bottom: 10px;">
			


						<!-- Add a new product -->
						
					
					<!-- <li><a href="{% url 'boutique:prod-add' shop.id %}">Add  New Product </a></li></ul> -->

					



										<div class="panel panel-default">
						<div class="panel-body">
							<center><h3><font face="Brush Script Std, Brush Script MT, cursive" size="200px" color="black">All Products</font></h3></center>

							<table class="table">
								<thread>
								
								<tr bgcolor="#cce6ff"><font color="red">
									<th>Name</th>
									<th>category</th>
									<th>Price</th>
									<th>picture</th>
									<th></th>
								</tr>
								</thread>	
								{% for product in shop.product_set.all %}
  
   <TR>

		<label for="product{{ forloop.counter }}">

			<TD>{{ product.product_name }} {{ product.boutique.id }}</TD>
			<TD>{{ product.product_category }}</TD>
			<TD>{{ product.product_price }}</TD>
	  
			<TD><img src="{{ product.product_logo.url }}" width="200" height="200" class="img-responsive"></TD>

			

			<TD><div>
			<form action="{% url 'boutique:edit_product' shop.id product.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="product_id" value="{{ product.id }}" />
            <button type="submit" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-edit"></span> Edit
            </button>
            </form>

			<!-- <a href="#" class="btn btn-primary btn-sm" role="button">Edit Product</a> --> 
			<a class="btn btn-primary btn-sm"   href="{% url 'boutique:duplicate_product' product.id %}">duplicate</a>
			<!-- <a class="btn btn-primary btn-sm"   href="{% url 'boutique:delete_product' shop.id product.id %}">duplicate</a> -->

  			<form action="{% url 'boutique:delete_product' shop.id product.id %}" method="post" style="display: inline;">
            {% csrf_token %}
            <input type="hidden" name="product_id" value="{{ product.id }}" />
            <button type="submit" class="btn btn-primary btn-sm">
            <span class="glyphicon glyphicon-remove"></span> Delete
            </button>
            </form>
			 </div></TD>

		</label>
	</TR>

{% endfor %} 
</TABLE>		

<!--  <a href="{% url 'boutique:prod-add' %}" class="btn btn-primary btn-sm" role="button">Add Product</a>
	
<TABLE border>
  <TR><TH>Name</TH><TH>category</TH><TH>price</TH></TR>
{% for product in shop.product_set.all %}
  
   <TR>

		<label for="product{{ forloop.counter }}">

			<TD>{{ product.product_name }}</TD>
			<TD>{{ product.product_category }}</TD>
			<TD>{{ product.product_price }}</TD>

		</label>
	</TR>
{% endfor %} 
</TABLE> -->


 

		
		
	<!-- <img src="{{ shop.shop_logo }}" style="width:200px; height:200px;">

	<h1>{{ shop.shop_name }}</h1> -->
	<!-- <h3>{{ shop.username }}</h3> -->
</div>
</div>

	{% if error_message %}
		<p><strong>{{ error_message }}</strong></p>
	{% endif %}




<!-- 		{% csrf_token %}
		{% for product in shop.product_set.all %}
			<input type="radio" id="product{{ forloop.counter }}" name="product" value="{{ product.id}}" />
			<li>
			<label for="product{{ forloop.counter }}">
				{{ product.product_name }}
			</label><br>
			</li>
		{% endfor %}  -->
{% endblock %}
</div>

boutique/templates/boutique/discover_shop.html
{% extends 'boutique/base.html' %}
{% block products_active %}active{% endblock %}

{% load staticfiles %}

{% block body %}
<br><br><br>
<div class="shops-container container-fluid">

    
        <div class="row"> 

                         <!-- ******* left ******* -->
    {% if products  %} 
            <div class="col-sm-4 col-md-3">
                <div class="panel panel-default">
                    <div class="panel-body">
                        <img src="{{ products.first.shop.shop_logo.url }}" class="img-responsive" style="width: 300px; height: 300px; float: left; margin-right: 10px;" />
                        <h2>{{ shop.shop_name }}</h2><br>
                        <p>Contact us and we'll get back to you within 24 hours</p>
                        <a href="{% url 'new_message' %}"><span class="glyphicon glyphicon-envelope"> Contact Shop</span></a><br>
                        <a href="{% url 'detail_album'  shop.user.id %}" ><span class="  glyphicon glyphicon-camera" aria-hidden="true"> Albums </span> </a>
                         <a href="{% url 'profile' shop.user.username %}"><h5><span class="glyphicon glyphicon-user"> owner </span></h5></a>
                    </div>
                </div>
            </div>
            

    


                       <!-- ****** Right ******* -->
    
        <div class="col-sm-8 col-md-9">
            <ul class="nav nav-pills" style="margin-bottom: 10px;">
            </ul>

            <div class="panel panel-default">
            <div class="panel-body">

                <center><h3><font color="black" face="Brush Script Std, Brush Script MT, cursive" size="200px" color="black">Shop of</font> <font color="#800040" face="Brush Script Std, Brush Script MT, cursive" size="200px" color="black"> {{shop.user.username}} </font></h3></center><br><br>
     
                {% for product in products %}

                    {% if product.is_activate == True %} 
                        <div class="col-sm-8 col-lg-4">
                            <div class="thumbnail">
                            <div class="caption">

                            <a href="{% url 'boutique:discover_product' product.id %}" method= "post">
                                <img src="{{ product.product_logo.url }}" class="img-responsive" style="width: 300px; float: left; margin-right: 300px; height:200px" />
                            </a>
                                <h2>{{ product.product_name}}</h2>
                                
                                <img src="{{ product.shop.shop_logo.url }}" class="img-responsive" style="width: 20px; height: 20px; float: left; margin-right: 10px;" />
                             
                                <a href="{% url 'boutique:discover_shop' product.shop.id %}">{{ product.shop.shop_name }}</a>
                               
                               
                                
                                <h3 style="float:right"><B>{{ product.product_price}} DT</B></h3>
                                <br><br><br>


                                    <!--  Reactions -->

                                {% include 'reactions/reaction.html' %}
                                <a  class="btn btn-default btn-md" role="button" href="javascript:void(0)" onclick="document.getElementById('{{ product.id }}').style.display='block';document.getElementById('{{ product.product_name }}').style.display='block'">
                           <span class="glyphicon glyphicon-star" style="color: gold"></span>
                       </a>

                    <div id="{{ product.id }}" class="white_content">

                        <a href="javascript:void(0)" onclick="document.getElementById('{{ product.id }}').style.display='none';document.getElementById('{{ product.product_name }}').style.display='none'">
                        <span class="glyphicon glyphicon-remove-circle pull-right" style="color: gold"></span></a>
                            <form role="form" action="{% url 'boutique:add_to_wishlist' product.id %}" method="post">
                            {% csrf_token %}
                            <div>
                            <fieldset data-role="controlgroup">
                                {% for wl,val in counter2 %}
                                    <div class="row center-block">
                                        <input style="margin-top: -1px" type="checkbox" name="{{ wl.name }}" id="checkbox-1a">
                                        <label>       {{ wl.name }} <span class="badge">{{val}}</span> </label>
                                    </div>
                                {% endfor %}
                            </fieldset>
                            <br><br>
                            <button style="margin-top: -20px;margin-bottom: -40px" type="submit" id="btnsub" class="ui-btn ui-corner-all ui-shadow ui-btn-a ui-btn-icon-left ui-icon-check">Submit</button>
                            </div>
                            </form>
                    </div>

      
                          <!--       <div display= inline-block>
                                <a href="#"><span class="badge" id="unread-count">0</span>LIKE</a>
                                <a href="#"><span class="badge" id="unread-count">0</span>wish</a>
                                <a href="#"><span class="badge" id="unread-count">0</span>share</a>
                                </div> -->
                                          <!--   <li><a href="{% url 'inbox' %}"><span class="badge pull-right" id="unread-count">0</span> Inbox</a></li> -->
                               

                            
                            </div>
                            </div>
                        </div>
                    {% endif %}
            
        
                {% endfor %}
                 <script src="{% static 'reaction/js/reactions.js' %}"></script>
                {% endif %}

</div></div>


{% endblock %}

boutique/templates/boutique/index.html
{% extends 'boutique/base.html' %}
{% block shops_active %}active{% endblock %}

{% block body %}
<br><br><br><br>
<div class="shops-container container-fluid">

    <!-- Shops -->
    <div class="row">
        <div class="col-sm-12">
            <center><h3>Welcome <FONT color="deeppink"; size=7; face="Satisfy">{{ user.username }} </FONT> to your shop!!</h3></center><br>
        </div>
        {% if shops %}

            {% for shop in shops %}
                <div class="col-sm-4 col-lg-4">
                    <div class="thumbnail">
                        <a href="{% url 'boutique:detail' shop.id %}">
                            <img src="{{ shop.shop_logo.url }}" class="img-responsive">
                        </a><center>
                        <div class="caption">
                            <h2>{{ shop.shop_name}}</h2>
                            <h4>{{ shop.username }}</h4>

                            <!-- View Details -->
                            <a href="{% url 'boutique:detail' shop.id %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                            
                        
                        </div></center>
                    </div>
                </div>
                {% cycle '' '' '' '' '' '<div class="clearfix visible-lg"></div>' %}
            {% endfor %}
    <div class="col-sm-4 col-md-7">      
        <div class="panel panel-default">
            <div class="panel-body">

                            <!--  Carousel products -->
                    <div id="myCarousel" class="carousel slide" data-ride="carousel">
                      <!-- Indicators -->
                       

                        <!-- Wrapper for slides -->
                        <div class="carousel-inner">
                                
                            <div class="item active">
                              {% for shop in shops %}
                              <center>
                              <img src="{{ shop.shop_logo.url }}" alt="" class="img-responsive" style="width: 500px; height: 350px">
                              </center>
                              <div class="carousel-caption">
                                <h3>My shop</h3>
                                <p>{{shop.shop_name}}</p>
                            </div>
                              {% endfor %}
                            </div>
                        {% for product in shops.first.product_set.all %}
                            <div class="item">
                             <center>
                              <img src="{{ product.product_logo.url }}" alt="" class="img-responsive" style="width: 500px; height: 350px">
                              </center>
                            </div>
                        {% endfor%}      

                        
                        </div>
                      <!-- Left and right controls -->
                    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
                        <span class="glyphicon glyphicon-chevron-left"></span>
                        <span class="sr-only">Previous</span>
                      </a>
                      <a class="right carousel-control" href="#myCarousel" data-slide="next">
                        <span class="glyphicon glyphicon-chevron-right"></span>
                        <span class="sr-only">Next</span>
                      </a>
                    </div>




        </div></div></div>
        {% else %}
            <div class="col-sm-12">
                <br><br><br><br><br><br>
                <center><FONT color="black"; size=3>You want to create your own shop ?</FONT></center>
                <br>
                <a href="{% url 'boutique:create_shop' %}">
                    <center><button type="button" class="btn btn-primary btn-lg">
                        <span class="glyphicon glyphicon-plus"></span>&nbsp; create a Shop
                    </button></center>
                </a>
            </div>
        {% endif %}
    </div>



</div>

{% endblock %}

boutique/templates/boutique/login.html
<!DOCTYPE html>
<html >
<head>
  <meta charset="UTF-8">
  <title>Login, Register form</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/normalize/5.0.0/normalize.min.css">
  <link rel='stylesheet prefetch' href='http://maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css'>
  {% load staticfiles %}
  <link rel="stylesheet" href="{% static 'boutique/style.css' %}" />


</head>

<body>

  <div class="login-box">
    <div class="lb-header">
      <a href="#" class="active" id="login-box-link">Login</a>
      <a href="#" id="signup-box-link">Sign Up</a>
    </div>
    <div class="social-login">
      <a href="#">
        <i class="fa fa-facebook fa-lg"></i>
        Login in with facebook
      </a>
      <a href="#">
        <i class="fa fa-google-plus fa-lg"></i>
        log in with Google
      </a>
    </div>
    <form method="post" action="{% url 'boutique:login_user'%}" class="email-login">
    {% csrf_token %}
      <div class="u-form-group">
        <input name="username" type="text" placeholder="Username"/>
      </div>
      <div class="u-form-group">
        <input name="password_login" type="password" placeholder="Password"/>
      </div>
      <div class="u-form-group">
        <button type="submit">Log in</button>
      </div>
      <div class="u-form-group">
        <a href="#" class="forgot-password">Forgot password?</a>
      </div>
    </form>

    
    <form method="post" action="{% url 'boutique:register'%}" class="email-signup">
    {% csrf_token %}
      <div class="u-form-group">
        <input name="username" type="text" placeholder="email"/>
      </div>
      <div class="u-form-group">
        <input name="password1" type="password" placeholder="Password"/>
      </div>
      <div class="u-form-group">
        <input name="password2" type="password" placeholder="Confirm Password"/>
      </div>
      
      <div class="u-form-group">
        <button type="submit">Sign Up</button>
      </div>
    </form>
  </div>


  <script src='http://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js'></script>
  <script src="{% static 'boutique/index.js' %}"></script>
</body>
</html>

boutique/templates/boutique/wishlist_products.html
                         <!-- ******* left ******* -->
    {% if products  %} 
           


                       <!-- ****** Right ******* -->
    
        <div class="col-sm-8 col-md-9">
        

            <div class="panel panel-default">
            <div class="panel-body">

                <center><h3><i class="fa fa-heart" aria-hidden="true"></i><i class="fa fa-heart" aria-hidden="true"></i><font color="black" face="Brush Script Std, Brush Script MT, cursive" size="200px" color="black"> Wishlist of</font> <font color="#800040" face="Brush Script Std, Brush Script MT, cursive" size="200px" color="black"> {{wishlist.user.username}}</font> <i class="fa fa-heart" aria-hidden="true"></i><i class="fa fa-heart" aria-hidden="true"></i></h3></center><br><br>
     
                {% for product in products %}

                    {% if product.is_activate == True %} 
                        <div class="col-sm-8 col-lg-4">
                            <div class="thumbnail">
                            <div class="caption">

                            <a href="{% url 'boutique:discover_product' product.id %}" method= "post">
                                <img src="{{ product.product_logo.url }}" class="img-responsive" style="width: 300px; float: left; margin-right: 300px; height:200px" />
                            </a>
                                <h2>{{ product.product_name}}</h2>
                                
                                <img src="{{ product.shop.shop_logo.url }}" class="img-responsive" style="width: 20px; height: 20px; float: left; margin-right: 10px;" />
                             
                                <a href="{% url 'boutique:discover_shop' product.shop.id %}">{{ product.shop.shop_name }}</a>
                               <a href="{% url 'profile' product.shop.user.username %}"><h5 style="display:inline; float:right;"><span class="glyphicon glyphicon-user"></span> {{ product.shop.user.username}} </h5></a><br>
                               
                                
                                <h3 ><B>{{ product.product_price}} DT</B></h3>
                                                            
                            </div>
                            </div>
                        </div>
                    {% endif %}
            
        
                {% endfor %}
       
                {% endif %}